# Generated by Django 5.0.1 on 2024-01-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_changeproductcountrequest_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeproductcountrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='changeproductcountrequest',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='INITIAL', max_length=16),
            preserve_default=False,
        ),
    ]
