# Generated by Django 5.0.1 on 2024-01-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_changeproductcountrequest_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changeproductcountrequest',
            old_name='new_count',
            new_name='new_amount',
        ),
    ]
