# Generated by Django 5.0.1 on 2024-01-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_new_count_changeproductcountrequest_new_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeproductcountrequest',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='INITIAL', max_length=16),
        ),
    ]
